project_id = "kvjgmqicictxxfnvhuwl"

[cron.whatsapp-agendamentos]
schedule = "* * * * *"
command = "SELECT net.http_post('https://kvjgmqicictxxfnvhuwl.supabase.co/functions/v1/processar-agendamentos-whatsapp', '{}', 'application/json', '{\"Authorization\": \"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2amdtcWljaWN0eHhmbnZodXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDU3NzIsImV4cCI6MjA2NTUyMTc3Mn0.gGPP76kvvjC6pKZMV9mbJawcccGKdMnLT1SLq6s56rY\"}'::jsonb);"

[cron.relatorios-ia-agendados]
schedule = "*/30 * * * *"
command = "SELECT net.http_post('https://kvjgmqicictxxfnvhuwl.supabase.co/functions/v1/processar-agendamentos-relatorios', '{}', 'application/json', '{\"Authorization\": \"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2amdtcWljaWN0eHhmbnZodXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDU3NzIsImV4cCI6MjA2NTUyMTc3Mn0.gGPP76kvvjC6pKZMV9mbJawcccGKdMnLT1SLq6s56rY\"}'::jsonb);"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://127.0.0.1:3000"

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[edge_functions]
enabled = true
port = 54323

[functions.exportar-funcionarios]
verify_jwt = false

[functions.gerar-escala]
verify_jwt = false

[functions.enviar-codigo]
verify_jwt = false

[functions.gerar-prontuario-diario]
verify_jwt = false

[functions.cronometro-prontuarios]
verify_jwt = false

[functions.enviar-whatsapp]
verify_jwt = false

[functions.processar-agendamentos-whatsapp]
verify_jwt = false

[functions.analisar-prontuarios]
verify_jwt = false

[functions.enviar-relatorio-email]
verify_jwt = false

[functions.processar-agendamentos-relatorios]
verify_jwt = false